[[models]]
provider = "anthropic"
id = "claude-3-5-sonnet-20240620"
aliases = []
recommended = true
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "anthropic"
id = "claude-3-5-sonnet-20241022"
aliases = []
recommended = true
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "anthropic"
id = "claude-3-7-sonnet-20250219"
aliases = []
recommended = true
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "anthropic"
id = "claude-3-5-haiku-20241022"
aliases = []
recommended = false

[[models]]
provider = "anthropic"
id = "claude-sonnet-4-20250514"
aliases = ["sonnet"]
recommended = true
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "anthropic"
id = "claude-opus-4-20250514"
aliases = []
recommended = true
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "anthropic"
id = "claude-opus-4-1-20250805"
aliases = ["opus"]
recommended = true
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "openai"
id = "gpt-4.1-2025-04-14"
aliases = ["gpt-4.1", "gpt4.1"]
recommended = false

[[models]]
provider = "openai"
id = "gpt-4.1-mini-2025-04-14"
aliases = []
recommended = false

[[models]]
provider = "openai"
id = "gpt-4.1-nano-2025-04-14"
aliases = []
recommended = false

[[models]]
provider = "openai"
id = "codex-mini-latest"
aliases = ["codex-mini"]
recommended = true
[models.parameters]
thinking_config.enabled = true
temperature = 1.0

[[models]]
provider = "openai"
id = "gpt-5-2025-08-07"
aliases = ["gpt-5", "gpt5"]
recommended = true
[models.parameters]
thinking_config.enabled = true
temperature = 1.0

[[models]]
provider = "openai"
id = "o3-2025-04-16"
aliases = ["o3"]
recommended = true
[models.parameters]
thinking_config.enabled = true
temperature = 1.0

[[models]]
provider = "openai"
id = "o3-pro-2025-06-10"
aliases = ["o3-pro"]
recommended = true
[models.parameters]
thinking_config.enabled = true
temperature = 1.0

[[models]]
provider = "openai"
id = "o4-mini-2025-04-16"
aliases = ["o4-mini"]
recommended = true
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "google"
id = "gemini-2.5-flash-preview-04-17"
aliases = []
recommended = false
[models.parameters]
thinking_config.enabled = true


[[models]]
provider = "google"
id = "gemini-2.5-pro-preview-06-05"
aliases = ["gemini"]
recommended = true
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "xai"
id = "grok-3"
aliases = []
recommended = true

[[models]]
provider = "xai"
id = "grok-3-mini"
aliases = ["grok-mini"]
recommended = false
[models.parameters]
thinking_config.enabled = true

[[models]]
provider = "xai"
id = "grok-4-0709"
aliases = ["grok"]
recommended = true
[models.parameters]
thinking_config.enabled = true
