[package]
name = "coder-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = [
    "full",
] } # Need full feature for parsing functions
quote = "1.0"
proc-macro2 = "1.0"
schemars = "0.8"
serde_json = "1.0"
