[package]
name = "conductor-proto"
version = "0.1.1"
edition = "2024"

[lints]
workspace = true

[dependencies]
tonic = "0.12"
prost = "0.13"
prost-types = "0.13"

[build-dependencies]
tonic-build = "0.12"
