[package]
name = "conductor-macros"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = [
    "full",
] } # Need full feature for parsing functions
quote = "1.0"
proc-macro2 = "1.0"
